# yaml-language-server: $schema=https://glasskube.dev/schemas/v1/package-manifest.json

name: clickhouse-operator
iconUrl: https://avatars.githubusercontent.com/u/54801242
shortDescription: Altinity Kubernetes Operator for ClickHouse
longDescription: >
  ClickHouse® is an open-source column-oriented database management system
  that allows generating analytical data reports in real-time.
  
  
  **Warning:** This operator is currently installed into the _kube-system_ namespace
references:
  - label: GitHub
    url: https://github.com/Altinity/clickhouse-operator
  - label: Documentation
    url: https://github.com/Altinity/clickhouse-operator/tree/master/docs
defaultNamespace: clickhouse-system
manifests:
  - url: https://raw.githubusercontent.com/Altinity/clickhouse-operator/0.23.6/deploy/operator/clickhouse-operator-install-bundle.yaml