kind: Cluster
apiVersion: postgresql.cnpg.io/v1
metadata:
  name: trieve-postgresql-keycloak
spec:
  enableSuperuserAccess: false
  instances: 2
  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak
  storage:
    size: 2Gi
  monitoring:
    enablePodMonitor: true