# yaml-language-server: $schema=https://glasskube.dev/schemas/v1/package-manifest.json

name: trieve
scope: Namespaced
shortDescription: Infrastructure for building AI search into your applications
longDescription: >
  All-in-one infrastructure for search, recommendations, RAG, and analytics offered via API
iconUrl: https://avatars.githubusercontent.com/u/122049913
defaultNamespace: default
dependencies:
  - name: "cloudnative-pg"
  - name: "clickhouse-operator"
helm:
  repositoryUrl: "oci://pmig/glasskube-trieve-demo/trieve"
  chartName: "trieve"
  chartVersion: "0.1.0"
  values:
    environment: server # Set to aws if deploying to
    domain: localtrieve.com # Only used if environment = local
    useGpu: false
    containers:
      keycloak:
        tag: 23.0.7
      minio:
        tag: RELEASE.2023-09-27T15-22-50Z
      tika:
        tag: 2.9.1.0-full
      mc:
        tag: latest
      server:
        tag: latest
      ingest:
        tag: latest
      file_worker:
        tag: latest
      delete_worker:
        tag: latest
      group_worker:
        tag: latest
      sync_qdrant:
        tag: latest
      search:
        tag: latest
      chat:
        tag: latest
      dashboard:
        tag: latest
      analytics:
        tag: latest
      clustering_cron:
        tag: latest
    postgres:
      useSubchart: true
      dbURI: postgres://postgres:password@trieve-postgresql.default.svc.cluster.local:5432 # Only used if useSubchart is false
    config:
      vite:
        apiHost: http://api.localtrieve.com/api
        searchUiUrl: http://search.localtrieve.com
        sentryChatDsn: https://********************************@sentry.trieve.ai/6
        dashboardUrl: http://dashboard.localtrieve.com
      redis:
        connections: 2
        useSubchart: true
        uri: "redis://:redis@trieve-redis-master.default.svc.cluster.local:6379" # Only used if useSubchart is false
      qdrant:
        useSubchart: true
        qdrantUrl: http://trieve-qdrant.default.svc.cluster.local:6334 # Only used if useSubchart is false
        collection: collection
        apiKey: "qdrant_password"
        quantizeVectors: false # If set to true will binary quantize
        replicationFactor: 0
        initCollections: true
        vectorSizes:
          - 768
          - 1024
          - 1536
          - 3072
      analytics:
        enabled: true
        clickhouseDB: default
        clickhouseUser: default
        clickhousePassword: password
        clickhouseUrl: http://chi-trieve-clickhouse-cluster1-0-0.clickhouse.svc.cluster.local:8123
      trieve:
        unlimited: true
        cookieSecure: false
        baseServerUrl: http://api.localtrieve.com
        embeddingServerOrigin: http://embedding-jina.default.svc.cluster.local
        sparseServerQueryOrigin: http://embedding-splade-query.default.svc.cluster.local
        sparseServerDocOrigin: http://embedding-splade-doc.default.svc.cluster.local
        embeddingServerOriginBGEM3: http://embedding-bgem3.default.svc.cluster.local
        rerankerServerOrigin: http://embedding-reranker.default.svc.cluster.local
        embeddingServerOriginJinaCode: https://api.jina.ai/v1
        jinaCodeApiKey: jina_************************************************************
        salt: goodsaltisveryyummy
        secretKey: 1234512345123451234512345123451234512345123451234512345123451234512345123451234h
        adminApiKey: admin
        anthropicAPIKey: sk-ant-***************************************
      oidc:
        clientSecret: YllmLDTy67MbsUBrUAWvQ7z9aMq0QcKx
        clientId: trieve
        issuerUrl: http://auth.localtrieve.com/realms/trieve
        authRedirectUrl: http://auth.localtrieve.com/realms/trieve/protocol/openid-connect/auth
      smtp:
        relay: smtp.gmail.com
        username: trieve@gmail.com
        passworD: pass************
        emailAddress: triever@gmail.com
      llm:
        apiKey: sk-or-v1-****************************************************************
      openai:
        apiKey: sk-************************************************
        baseUrl: https://api.openai.com/v1
      s3:
        endpoint:
        accessKey: ZaaZZaaZZaaZZaaZZaaZ
        secretKey: ssssssssssssssssssssTTTTTTTTTTTTTTTTTTTT
        bucket: trieve
        region: us-east-1
      stripe:
        secret: sk_test_***************************************************************************************************
        webhookSecret: sk_test_***************************************************************************************************
        adminDashboardUrl: http://dashboard.localtrieve.com
    embeddings:
      - name: jina
        revision: main
        model: jinaai/jina-embeddings-v2-base-en
        revision: main
        args: [ ]
      - name: reranker
        model: BAAI/bge-reranker-large
        revision: refs/pr/4
        args: [ ]
      - name: splade-doc
        model: naver/efficient-splade-VI-BT-large-doc
        revision: main
        args: [ "--pooling", "splade" ]
      - name: splade-query
        model: naver/efficient-splade-VI-BT-large-query
        revision: main
        args: [ "--pooling", "splade" ]

