apiVersion: apps/v1
kind: Deployment
metadata:
  name: trieve-ingest
spec:
  selector: {}
  template:
    spec:
      containers:
        - name: ingest
          image: trieve/ingest
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: trieve-postgresql-server-app
                  key: uri
            - name: QDRANT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: trieve-qdrant-qdrant-apikey
                  key: api-key
          envFrom:
            - configMapRef:
                name: trieve-server-config
          resources:
            limits:
              cpu: "1"
              memory: 100Mi
