commonLabels:
  app.kubernetes.io/component: trieve-ui-chat
nameSuffix: -chat
resources:
  - ../base
patches:
  - target:
      kind: Ingress
      name: trieve-ui
    patch: |-
      - op: add
        path: /spec/rules/0/host
        value: chat.localtrieve.com
images:
  - name: ui
    newName: trieve/chat
    newTag: latest
