apiVersion: apps/v1
kind: Deployment
metadata:
  name: trieve-embedding
spec:
  selector: {}
  template:
    spec:
      containers:
        - name: embedding
          args:
            - --model-id
            - BAAI/bge-reranker-large
            - --revision
            - refs/pr/4
